// packages/bunshi/src/components/controls/Input.tsx
import { getLocaleValue, type Props, type InputProps } from "../../lib";

import withLabel from "./WithLabel";

type ExtendedInputProps = {
  value: string;
  onChange: (value: string) => void;
} & Pick<InputProps, "inputType" | "type"> &
  Pick<Props, "description">;

export default withLabel(
  function Input({
    value,
    description,
    onChange,
    inputType,
    type,
  }: ExtendedInputProps) {
    const As = inputType ?? "input";
    return (
      <div className="flex border border-black rounded focus-within:ring-3 focus-within:ring-black/50">
        <As
          type={type}
          placeholder={getLocaleValue(description)}
          value={value}
          onChange={(event) => onChange(event.target.value)}
          className="flex-1 bg-transparent p-2 outline-none placeholder-black/50"
        />
      </div>
    );
  },
  { showDescription: false }
);

// packages/widgets/src/components/Input.vue
<script lang="ts" setup>
type Props = {
  icon?: string;
  placeholder: string;
  name: string;
  type: "email" | "text";
};

const props = defineProps<Props>();
const model = defineModel<string>();
</script>
<template>
  <div
    class="input flex items-center space-x-2 border-1 border-black bg-white px-2 rounded focus-within:ring-3 focus-within:ring-black/50"
  >
    <div
      v-if="icon"
      :class="icon"
      class="icon text-lg text-black/50"
    />
    <input
      v-model="model"
      v-bind="props"
      class="flex-1 bg-transparent placeholder-black/50 py-2 focus:outline-none"
    />
  </div>
</template>
<style scoped>
.input:focus-within .icon {
  color: black;
}
</style>
